
/* Modo de Uso:
SIMBOLO (Ex: >= ) - Maior ou igual
PERCE (Ex: 75 ) - Percentual de conclusão
*/


IF :SIMBOLO = '>='
BEGIN

SELECT
	GFILIAL.NOMEFANTASIA AS 'UNIDADE',
	STIPOCURSO.NOME AS 'NIVEL ENSINO',
	SALUNO.RA,
	PPESSOA.NOME AS 'ALUNO',
	PPESSOA.CPF,
	SGRADE.DESCRICAO AS 'MATRIZ',
	SCAMPUS.DESCRICAO AS 'CAMPUS',
	SCAMPUS.CAMPUSMEC,
	SCURSO.NOME AS 'CURSO',
	STURNO.NOME AS 'TURNO',
	SCURSOMEC.CODINEPCURSO AS 'CODEMEC CURSO',
	SINSTITUICAOMEC.CODEMEC AS 'CODEMEC INSTITUICAO',
	SINSTITUICAO.NOMEFANTASIA AS 'ESCOLA',
	SSTATUS.DESCRICAO AS 'STATUS CURSO',
	SGRAU.DESCRICAO AS 'GRAU',
	SPESSOA.ANOULTIMAINST AS 'CONCLUSAO ENSINO MEDIO',
	PENDENTES.TOTAL AS 'DISCIPLINAS PENDENTES',
	DTPERLET.DTINICIO AS 'DTINGRESSO',
	B.TCOMPOMENTE 'TOTAL O.C.C',
	A.TOTALATIV 'O.C.C CONCLUIDOS',
	ISNULL(CAST(CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA - B.TCOMPOMENTE) ) AS DECIMAL(10,2)) AS VARCHAR),0) + '%' AS 'CONCLUIDO',
	ISNULL(CAST(CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA) ) AS DECIMAL(10,2)) AS VARCHAR),0) + '%' AS 'CONCLUIDO SEM O.C.C',
		CASE WHEN (100 - CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA - B.TCOMPOMENTE) ) AS DECIMAL(10,2))) - A.EMCURSO < 0 THEN '0%'
	ELSE CAST((100 - CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA - B.TCOMPOMENTE) ) AS DECIMAL(10,2))) - A.EMCURSO AS VARCHAR) + '%'
	END AS 'RESTANTE',
			CASE WHEN (100 - CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA) ) AS DECIMAL(10,2))) - A.EMCURSO < 0 THEN '0%'
	ELSE CAST((100 - CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA) ) AS DECIMAL(10,2))) - A.EMCURSO AS VARCHAR) + '%'
	END AS 'RESTANTE SEM O.C.C',
	A.EMCURSO,
	SGRADE.CARGAHORARIA
	
FROM SHISTDISCCONCLUIDAS
INNER JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL
INNER JOIN SCURSO ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO



OUTER APPLY (
SELECT 
	MIN(SPLETIVO.DTINICIO) AS DTINICIO,
	SMATRICPL.RA,
	SHF.CODCURSO,
	SMATRICPL.CODCOLIGADA
FROM SMATRICPL
INNER JOIN SPLETIVO ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
	AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
INNER JOIN SHABILITACAOFILIAL SHF ON SHF.CODCOLIGADA = SMATRICPL.CODCOLIGADA
	AND SHF.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
WHERE SMATRICPL.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND SMATRICPL.RA = SHISTDISCCONCLUIDAS.RA
	AND SHF.CODCURSO = SHABILITACAOFILIAL.CODCURSO
GROUP BY SHF.CODCURSO,
SMATRICPL.RA,
SMATRICPL.CODCOLIGADA

) AS DTPERLET



LEFT JOIN (

SELECT 
	SUM(SHISTDISCOPTELETIVAS.CH) AS 'TOPTATIVAS',
	SHISTDISCOPTELETIVAS.CODCOLIGADA,
	SHISTDISCOPTELETIVAS.RA,
	SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL
FROM SHISTDISCOPTELETIVAS
INNER JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.CODCOLIGADA = SHISTDISCOPTELETIVAS.CODCOLIGADA
	AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL
INNER JOIN SGRADE (NOLOCK) ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
	AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE

OUTER APPLY(
SELECT SUM(SCP.VALORMINIMO) AS 'TCOMPOMENTE'
FROM SCOMPONENTECURRICULAR SCP
WHERE SCP.CODCOLIGADA = SHISTDISCOPTELETIVAS.CODCOLIGADA
	AND SCP.IDHABILITACAOFILIAL = SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL
) AS D

WHERE SGRADE.STATUS <> 1
AND SHISTDISCOPTELETIVAS.STATUS LIKE '%APROVADO%'
GROUP BY SHISTDISCOPTELETIVAS.CODCOLIGADA,
	SHISTDISCOPTELETIVAS.RA,
	SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL

) AS OPT ON OPT.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND OPT.RA = SHISTDISCCONCLUIDAS.RA
	AND OPT.IDHABILITACAOFILIAL = SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL


OUTER APPLY(
SELECT SUM(VALORMINIMO) AS 'TCOMPOMENTE'
FROM SCOMPONENTECURRICULAR 
WHERE SCOMPONENTECURRICULAR.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SCOMPONENTECURRICULAR.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
) AS B


INNER JOIN GFILIAL ON GFILIAL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND GFILIAL.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL
LEFT JOIN SFILIAL ON SFILIAL.CODCOLIGADA = GFILIAL.CODCOLIGADA
	AND SFILIAL.CODFILIAL = GFILIAL.CODFILIAL
LEFT JOIN SINSTITUICAOMEC ON SINSTITUICAOMEC.CODCOLIGADA = SFILIAL.CODCOLIGADA
	AND SINSTITUICAOMEC.CODFILIAL = SFILIAL.CODFILIAL
INNER JOIN STIPOCURSO ON STIPOCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
INNER JOIN STURNO ON STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO
INNER JOIN SHABILITACAOALUNO ON SHABILITACAOALUNO.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL
	AND SHABILITACAOALUNO.RA = SHISTDISCCONCLUIDAS.RA
LEFT JOIN SCAMPUS ON SCAMPUS.CODCAMPUS = SHABILITACAOALUNO.CODCAMPUS
LEFT JOIN SSTATUS ON SSTATUS.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
	AND SSTATUS.CODSTATUS = SHABILITACAOALUNO.CODSTATUS
LEFT JOIN SCURSOMEC ON SCURSOMEC.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SCURSOMEC.IDCURSOMEC = SHABILITACAOFILIAL.IDCURSOMEC
INNER JOIN SGRADE (NOLOCK) ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
	AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
INNER JOIN SALUNO ON SALUNO.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND SALUNO.RA = SHISTDISCCONCLUIDAS.RA
INNER JOIN PPESSOA ON PPESSOA.CODIGO = SALUNO.CODPESSOA
LEFT JOIN SPESSOA ON SPESSOA.CODIGO = PPESSOA.CODIGO
LEFT JOIN SINSTITUICAO ON SINSTITUICAO.CODINST = SPESSOA.CODINST2GRAU
LEFT JOIN SGRAU ON SGRAU.CODGRAU = SPESSOA.GRAUULTIMAINST
	



OUTER APPLY (

SELECT 
	SHD.CODCOLIGADA,
	SHD.RA,
	SHD.IDHABILITACAOFILIAL,
	SUM(SHD.CH) AS 'TDISC'
FROM SHISTDISCCONCLUIDAS SHD
INNER JOIN SHABILITACAOFILIAL SHF ON SHF.CODCOLIGADA = SHD.CODCOLIGADA
	AND SHF.IDHABILITACAOFILIAL = SHD.IDHABILITACAOFILIAL
INNER JOIN SDISCGRADE SDG (NOLOCK) ON SDG.CODCOLIGADA = SHF.CODCOLIGADA
	AND SDG.CODCURSO = SHF.CODCURSO
	AND SDG.CODHABILITACAO = SHF.CODHABILITACAO
	AND SDG.CODGRADE = SHF.CODGRADE
	AND SDG.CODDISC = SHD.CODDISC
LEFT JOIN SDISCGRADECOMPL SDGC ON SDG.CODCOLIGADA = SDGC.CODCOLIGADA
	AND SDG.CODCURSO = SDGC.CODCURSO
	AND SDG.CODHABILITACAO = SDGC.CODHABILITACAO
	AND SDG.CODGRADE = SDGC.CODGRADE
	AND SDG.CODPERIODO = SDGC.CODPERIODO
	AND SDG.CODDISC = SDGC.CODDISC

WHERE SDGC.ZERARCREDFINRECALC IS NULL
	AND SHD.CODCOLIGADA = SGRADE.CODCOLIGADA
	AND SHD.RA = SHISTDISCCONCLUIDAS.RA
	AND SHD.IDHABILITACAOFILIAL = SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL

GROUP BY SHD.CODCOLIGADA,
	SHD.RA,
	SHD.IDHABILITACAOFILIAL
) AS DISCGRADE



LEFT JOIN (

SELECT 
	/*CAST(CAST((((SUM(SHISTDISCPENDENTES.CH) + CASE WHEN ATALU.TATIV >= C.TCOMPOMENTE THEN 0 ELSE (C.TCOMPOMENTE - ATALU.TATIV) END) *100) / SGRADE.CARGAHORARIA) AS DECIMAL(10,2)) AS VARCHAR) + '%' AS 'PENDENTE',*/
	ISNULL(CAST(((SUM(SHISTDISCPENDENTES.CH) *100) / (SGRADE.CARGAHORARIA - C.TCOMPOMENTE)  ) AS DECIMAL(10,2)),0) AS 'EMCURSO',
	SHISTDISCPENDENTES.CODCOLIGADA,
	SHISTDISCPENDENTES.RA,
	SHISTDISCPENDENTES.IDHABILITACAOFILIAL,
	SUM(SHISTDISCPENDENTES.CH) AS 'DISCEMCURSO',
	CASE WHEN ATALU.TATIV >= C.TCOMPOMENTE THEN C.TCOMPOMENTE ELSE (C.TCOMPOMENTE - ATALU.TATIV) END TOTALATIV
FROM SHISTDISCPENDENTES
INNER JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
	AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHISTDISCPENDENTES.IDHABILITACAOFILIAL
INNER JOIN SGRADE (NOLOCK) ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
	AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE

INNER JOIN SHABILITACAOFILIAL SHF ON SHF.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
	AND SHF.IDHABILITACAOFILIAL = SHISTDISCPENDENTES.IDHABILITACAOFILIAL
INNER JOIN SDISCGRADE SDG (NOLOCK) ON SDG.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
	AND SDG.CODCURSO = SHF.CODCURSO
	AND SDG.CODHABILITACAO = SHF.CODHABILITACAO
	AND SDG.CODGRADE = SHF.CODGRADE
	AND SDG.CODDISC = SHISTDISCPENDENTES.CODDISC
LEFT JOIN SDISCGRADECOMPL SDGC ON SDG.CODCOLIGADA = SDGC.CODCOLIGADA
	AND SDG.CODCURSO = SDGC.CODCURSO
	AND SDG.CODHABILITACAO = SDGC.CODHABILITACAO
	AND SDG.CODGRADE = SDGC.CODGRADE
	AND SDG.CODPERIODO = SDGC.CODPERIODO
	AND SDG.CODDISC = SDGC.CODDISC


OUTER APPLY(
SELECT SUM(SC.VALORMINIMO) AS 'TCOMPOMENTE'
FROM SCOMPONENTECURRICULAR SC
WHERE SC.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
	AND SC.IDHABILITACAOFILIAL = SHISTDISCPENDENTES.IDHABILITACAOFILIAL
) AS C


OUTER APPLY(

SELECT SUM(CARGAHORARIAATV) AS 'TATIV'
FROM SATIVIDADEALUNO
WHERE SATIVIDADEALUNO.RA = SHISTDISCPENDENTES.RA
AND SATIVIDADEALUNO.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
AND SATIVIDADEALUNO.IDHABILITACAOFILIAL = SHISTDISCPENDENTES.IDHABILITACAOFILIAL
AND SATIVIDADEALUNO.CUMPRIUATIVIDADE = 'S'
) AS ATALU


WHERE SGRADE.STATUS <> 1
AND SHISTDISCPENDENTES.STATUS IS NOT NULL
AND SDGC.ZERARCREDFINRECALC IS NULL
GROUP BY SGRADE.CARGAHORARIA,
	SHISTDISCPENDENTES.CODCOLIGADA,
	SHISTDISCPENDENTES.RA,
	ATALU.TATIV,
	C.TCOMPOMENTE,
	SHISTDISCPENDENTES.IDHABILITACAOFILIAL

) AS A ON A.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND A.RA = SHISTDISCCONCLUIDAS.RA
	AND A.IDHABILITACAOFILIAL = SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL
	
	
	
OUTER APPLY (

SELECT 
	SHISTDISCPENDENTES.CODCOLIGADA,
	SHISTDISCPENDENTES.RA,
	SHISTDISCPENDENTES.IDHABILITACAOFILIAL,
	COUNT(*) AS TOTAL

FROM SHISTDISCPENDENTES

INNER JOIN SHABILITACAOFILIAL SHF ON SHF.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
	AND SHF.IDHABILITACAOFILIAL = SHISTDISCPENDENTES.IDHABILITACAOFILIAL
INNER JOIN SDISCGRADE SDG (NOLOCK) ON SDG.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
	AND SDG.CODCURSO = SHF.CODCURSO
	AND SDG.CODHABILITACAO = SHF.CODHABILITACAO
	AND SDG.CODGRADE = SHF.CODGRADE
	AND SDG.CODDISC = SHISTDISCPENDENTES.CODDISC
LEFT JOIN SDISCGRADECOMPL SDGC ON SDG.CODCOLIGADA = SDGC.CODCOLIGADA
	AND SDG.CODCURSO = SDGC.CODCURSO
	AND SDG.CODHABILITACAO = SDGC.CODHABILITACAO
	AND SDG.CODGRADE = SDGC.CODGRADE
	AND SDG.CODPERIODO = SDGC.CODPERIODO
	AND SDG.CODDISC = SDGC.CODDISC


WHERE	 SHISTDISCPENDENTES.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND SHISTDISCPENDENTES.RA = SHISTDISCCONCLUIDAS.RA
	AND SHISTDISCPENDENTES.IDHABILITACAOFILIAL = SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL
	AND SDGC.ZERARCREDFINRECALC IS NULL
GROUP BY 
	SHISTDISCPENDENTES.CODCOLIGADA,
	SHISTDISCPENDENTES.RA,
	SHISTDISCPENDENTES.IDHABILITACAOFILIAL


) AS PENDENTES
	
	

WHERE SGRADE.STATUS <> 1
AND SHABILITACAOFILIAL.CODTIPOCURSO = 1



GROUP BY SGRADE.CARGAHORARIA,
A.EMCURSO,
SALUNO.RA,
SINSTITUICAO.NOMEFANTASIA,
PPESSOA.NOME,
SHABILITACAOFILIAL.IDHABILITACAOFILIAL,
PPESSOA.CPF,
A.TOTALATIV,
SSTATUS.DESCRICAO,
GFILIAL.NOMEFANTASIA,
STIPOCURSO.NOME,
SCAMPUS.DESCRICAO,
SCAMPUS.CAMPUSMEC,
OPT.TOPTATIVAS,
PENDENTES.TOTAL,
SCURSOMEC.CODINEPCURSO,
DISCGRADE.TDISC,
SCURSO.NOME,
DTPERLET.DTINICIO,
SGRADE.DESCRICAO,
B.TCOMPOMENTE,
SPESSOA.ANOULTIMAINST,
A.DISCEMCURSO,
STURNO.NOME,
SINSTITUICAOMEC.CODEMEC,
SGRAU.DESCRICAO,
SCURSO.CODCURSO




HAVING ISNULL(CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA - B.TCOMPOMENTE) ) AS DECIMAL(10,2)),0) >= :PERCE
AND SCURSO.CODCURSO = :CODCURSO
	


END
ELSE IF :SIMBOLO = '<=' BEGIN


SELECT
	GFILIAL.NOMEFANTASIA AS 'UNIDADE',
	STIPOCURSO.NOME AS 'NIVEL ENSINO',
	SALUNO.RA,
	PPESSOA.NOME AS 'ALUNO',
	PPESSOA.CPF,
	SGRADE.DESCRICAO AS 'MATRIZ',
	SCURSO.NOME AS 'CURSO',
	STURNO.NOME AS 'TURNO',
	SCAMPUS.DESCRICAO AS 'CAMPUS',
	SCAMPUS.CAMPUSMEC,
	SCURSOMEC.CODINEPCURSO AS 'CODEMEC CURSO',
	SINSTITUICAOMEC.CODEMEC AS 'CODEMEC INSTITUICAO',
	SINSTITUICAO.NOMEFANTASIA AS 'ESCOLA',
	SSTATUS.DESCRICAO AS 'STATUS CURSO',
	SGRAU.DESCRICAO AS 'GRAU',
	SPESSOA.ANOULTIMAINST AS 'CONCLUSAO ENSINO MEDIO',
	PENDENTES.TOTAL AS 'DISCIPLINAS PENDENTES',
	DTPERLET.DTINICIO AS 'DTINGRESSO',
	B.TCOMPOMENTE 'TOTAL O.C.C',
	A.TOTALATIV 'O.C.C CONCLUIDOS',
	ISNULL(CAST(CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA - B.TCOMPOMENTE) ) AS DECIMAL(10,2)) AS VARCHAR),0) + '%' AS 'CONCLUIDO',
	ISNULL(CAST(CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA) ) AS DECIMAL(10,2)) AS VARCHAR),0) + '%' AS 'CONCLUIDO SEM O.C.C',
		CASE WHEN (100 - CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA - B.TCOMPOMENTE) ) AS DECIMAL(10,2))) - A.EMCURSO < 0 THEN '0%'
	ELSE CAST((100 - CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA - B.TCOMPOMENTE) ) AS DECIMAL(10,2))) - A.EMCURSO AS VARCHAR) + '%'
	END AS 'RESTANTE',
			CASE WHEN (100 - CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA) ) AS DECIMAL(10,2))) - A.EMCURSO < 0 THEN '0%'
	ELSE CAST((100 - CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA) ) AS DECIMAL(10,2))) - A.EMCURSO AS VARCHAR) + '%'
	END AS 'RESTANTE SEM O.C.C',
	A.EMCURSO,
	SGRADE.CARGAHORARIA
	
FROM SHISTDISCCONCLUIDAS
INNER JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL
INNER JOIN SCURSO ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO



OUTER APPLY (
SELECT 
	MIN(SPLETIVO.DTINICIO) AS DTINICIO,
	SMATRICPL.RA,
	SHF.CODCURSO,
	SMATRICPL.CODCOLIGADA
FROM SMATRICPL
INNER JOIN SPLETIVO ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
	AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
INNER JOIN SHABILITACAOFILIAL SHF ON SHF.CODCOLIGADA = SMATRICPL.CODCOLIGADA
	AND SHF.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
WHERE SMATRICPL.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND SMATRICPL.RA = SHISTDISCCONCLUIDAS.RA
	AND SHF.CODCURSO = SHABILITACAOFILIAL.CODCURSO
GROUP BY SHF.CODCURSO,
SMATRICPL.RA,
SMATRICPL.CODCOLIGADA

) AS DTPERLET


LEFT JOIN (

SELECT 
	SUM(SHISTDISCOPTELETIVAS.CH) AS 'TOPTATIVAS',
	SHISTDISCOPTELETIVAS.CODCOLIGADA,
	SHISTDISCOPTELETIVAS.RA,
	SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL
FROM SHISTDISCOPTELETIVAS
INNER JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.CODCOLIGADA = SHISTDISCOPTELETIVAS.CODCOLIGADA
	AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL
INNER JOIN SGRADE (NOLOCK) ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
	AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE

OUTER APPLY(
SELECT SUM(SCP.VALORMINIMO) AS 'TCOMPOMENTE'
FROM SCOMPONENTECURRICULAR SCP
WHERE SCP.CODCOLIGADA = SHISTDISCOPTELETIVAS.CODCOLIGADA
	AND SCP.IDHABILITACAOFILIAL = SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL
) AS D

WHERE SGRADE.STATUS <> 1
AND SHISTDISCOPTELETIVAS.STATUS LIKE '%APROVADO%'
GROUP BY SHISTDISCOPTELETIVAS.CODCOLIGADA,
	SHISTDISCOPTELETIVAS.RA,
	SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL

) AS OPT ON OPT.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND OPT.RA = SHISTDISCCONCLUIDAS.RA
	AND OPT.IDHABILITACAOFILIAL = SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL


OUTER APPLY(
SELECT SUM(VALORMINIMO) AS 'TCOMPOMENTE'
FROM SCOMPONENTECURRICULAR 
WHERE SCOMPONENTECURRICULAR.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SCOMPONENTECURRICULAR.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
) AS B


INNER JOIN GFILIAL ON GFILIAL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND GFILIAL.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL
LEFT JOIN SFILIAL ON SFILIAL.CODCOLIGADA = GFILIAL.CODCOLIGADA
	AND SFILIAL.CODFILIAL = GFILIAL.CODFILIAL
LEFT JOIN SINSTITUICAOMEC ON SINSTITUICAOMEC.CODCOLIGADA = SFILIAL.CODCOLIGADA
	AND SINSTITUICAOMEC.CODFILIAL = SFILIAL.CODFILIAL
INNER JOIN STIPOCURSO ON STIPOCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
INNER JOIN STURNO ON STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO
INNER JOIN SHABILITACAOALUNO ON SHABILITACAOALUNO.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL
	AND SHABILITACAOALUNO.RA = SHISTDISCCONCLUIDAS.RA
LEFT JOIN SCAMPUS ON SCAMPUS.CODCAMPUS = SHABILITACAOALUNO.CODCAMPUS
LEFT JOIN SSTATUS ON SSTATUS.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
	AND SSTATUS.CODSTATUS = SHABILITACAOALUNO.CODSTATUS
LEFT JOIN SCURSOMEC ON SCURSOMEC.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SCURSOMEC.IDCURSOMEC = SHABILITACAOFILIAL.IDCURSOMEC
INNER JOIN SGRADE (NOLOCK) ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
	AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
INNER JOIN SALUNO ON SALUNO.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND SALUNO.RA = SHISTDISCCONCLUIDAS.RA
INNER JOIN PPESSOA ON PPESSOA.CODIGO = SALUNO.CODPESSOA
LEFT JOIN SPESSOA ON SPESSOA.CODIGO = PPESSOA.CODIGO
LEFT JOIN SINSTITUICAO ON SINSTITUICAO.CODINST = SPESSOA.CODINST2GRAU
LEFT JOIN SGRAU ON SGRAU.CODGRAU = SPESSOA.GRAUULTIMAINST
	



OUTER APPLY (

SELECT 
	SHD.CODCOLIGADA,
	SHD.RA,
	SHD.IDHABILITACAOFILIAL,
	SUM(SHD.CH) AS 'TDISC'
FROM SHISTDISCCONCLUIDAS SHD
INNER JOIN SHABILITACAOFILIAL SHF ON SHF.CODCOLIGADA = SHD.CODCOLIGADA
	AND SHF.IDHABILITACAOFILIAL = SHD.IDHABILITACAOFILIAL
INNER JOIN SDISCGRADE SDG (NOLOCK) ON SDG.CODCOLIGADA = SHF.CODCOLIGADA
	AND SDG.CODCURSO = SHF.CODCURSO
	AND SDG.CODHABILITACAO = SHF.CODHABILITACAO
	AND SDG.CODGRADE = SHF.CODGRADE
	AND SDG.CODDISC = SHD.CODDISC
LEFT JOIN SDISCGRADECOMPL SDGC ON SDG.CODCOLIGADA = SDGC.CODCOLIGADA
	AND SDG.CODCURSO = SDGC.CODCURSO
	AND SDG.CODHABILITACAO = SDGC.CODHABILITACAO
	AND SDG.CODGRADE = SDGC.CODGRADE
	AND SDG.CODPERIODO = SDGC.CODPERIODO
	AND SDG.CODDISC = SDGC.CODDISC

WHERE SDGC.ZERARCREDFINRECALC IS NULL
	AND SHD.CODCOLIGADA = SGRADE.CODCOLIGADA
	AND SHD.RA = SHISTDISCCONCLUIDAS.RA
	AND SHD.IDHABILITACAOFILIAL = SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL

GROUP BY SHD.CODCOLIGADA,
	SHD.RA,
	SHD.IDHABILITACAOFILIAL
) AS DISCGRADE



LEFT JOIN (

SELECT 
	/*CAST(CAST((((SUM(SHISTDISCPENDENTES.CH) + CASE WHEN ATALU.TATIV >= C.TCOMPOMENTE THEN 0 ELSE (C.TCOMPOMENTE - ATALU.TATIV) END) *100) / SGRADE.CARGAHORARIA) AS DECIMAL(10,2)) AS VARCHAR) + '%' AS 'PENDENTE',*/
	ISNULL(CAST(((SUM(SHISTDISCPENDENTES.CH) *100) / (SGRADE.CARGAHORARIA - C.TCOMPOMENTE)  ) AS DECIMAL(10,2)),0) AS 'EMCURSO',
	SHISTDISCPENDENTES.CODCOLIGADA,
	SHISTDISCPENDENTES.RA,
	SHISTDISCPENDENTES.IDHABILITACAOFILIAL,
	SUM(SHISTDISCPENDENTES.CH) AS 'DISCEMCURSO',
	CASE WHEN ATALU.TATIV >= C.TCOMPOMENTE THEN C.TCOMPOMENTE ELSE (C.TCOMPOMENTE - ATALU.TATIV) END TOTALATIV
FROM SHISTDISCPENDENTES
INNER JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
	AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHISTDISCPENDENTES.IDHABILITACAOFILIAL
INNER JOIN SGRADE (NOLOCK) ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
	AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE

INNER JOIN SHABILITACAOFILIAL SHF ON SHF.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
	AND SHF.IDHABILITACAOFILIAL = SHISTDISCPENDENTES.IDHABILITACAOFILIAL
INNER JOIN SDISCGRADE SDG (NOLOCK) ON SDG.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
	AND SDG.CODCURSO = SHF.CODCURSO
	AND SDG.CODHABILITACAO = SHF.CODHABILITACAO
	AND SDG.CODGRADE = SHF.CODGRADE
	AND SDG.CODDISC = SHISTDISCPENDENTES.CODDISC
LEFT JOIN SDISCGRADECOMPL SDGC ON SDG.CODCOLIGADA = SDGC.CODCOLIGADA
	AND SDG.CODCURSO = SDGC.CODCURSO
	AND SDG.CODHABILITACAO = SDGC.CODHABILITACAO
	AND SDG.CODGRADE = SDGC.CODGRADE
	AND SDG.CODPERIODO = SDGC.CODPERIODO
	AND SDG.CODDISC = SDGC.CODDISC


OUTER APPLY(
SELECT SUM(SC.VALORMINIMO) AS 'TCOMPOMENTE'
FROM SCOMPONENTECURRICULAR SC
WHERE SC.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
	AND SC.IDHABILITACAOFILIAL = SHISTDISCPENDENTES.IDHABILITACAOFILIAL
) AS C


OUTER APPLY(

SELECT SUM(CARGAHORARIAATV) AS 'TATIV'
FROM SATIVIDADEALUNO
WHERE SATIVIDADEALUNO.RA = SHISTDISCPENDENTES.RA
AND SATIVIDADEALUNO.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
AND SATIVIDADEALUNO.IDHABILITACAOFILIAL = SHISTDISCPENDENTES.IDHABILITACAOFILIAL
AND SATIVIDADEALUNO.CUMPRIUATIVIDADE = 'S'
) AS ATALU


WHERE SGRADE.STATUS <> 1
AND SHISTDISCPENDENTES.STATUS IS NOT NULL
AND SDGC.ZERARCREDFINRECALC IS NULL
GROUP BY SGRADE.CARGAHORARIA,
	SHISTDISCPENDENTES.CODCOLIGADA,
	SHISTDISCPENDENTES.RA,
	ATALU.TATIV,
	C.TCOMPOMENTE,
	SHISTDISCPENDENTES.IDHABILITACAOFILIAL

) AS A ON A.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND A.RA = SHISTDISCCONCLUIDAS.RA
	AND A.IDHABILITACAOFILIAL = SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL
	
	
	
OUTER APPLY (

SELECT 
	SHISTDISCPENDENTES.CODCOLIGADA,
	SHISTDISCPENDENTES.RA,
	SHISTDISCPENDENTES.IDHABILITACAOFILIAL,
	COUNT(*) AS TOTAL

FROM SHISTDISCPENDENTES

INNER JOIN SHABILITACAOFILIAL SHF ON SHF.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
	AND SHF.IDHABILITACAOFILIAL = SHISTDISCPENDENTES.IDHABILITACAOFILIAL
INNER JOIN SDISCGRADE SDG (NOLOCK) ON SDG.CODCOLIGADA = SHISTDISCPENDENTES.CODCOLIGADA
	AND SDG.CODCURSO = SHF.CODCURSO
	AND SDG.CODHABILITACAO = SHF.CODHABILITACAO
	AND SDG.CODGRADE = SHF.CODGRADE
	AND SDG.CODDISC = SHISTDISCPENDENTES.CODDISC
LEFT JOIN SDISCGRADECOMPL SDGC ON SDG.CODCOLIGADA = SDGC.CODCOLIGADA
	AND SDG.CODCURSO = SDGC.CODCURSO
	AND SDG.CODHABILITACAO = SDGC.CODHABILITACAO
	AND SDG.CODGRADE = SDGC.CODGRADE
	AND SDG.CODPERIODO = SDGC.CODPERIODO
	AND SDG.CODDISC = SDGC.CODDISC


WHERE	 SHISTDISCPENDENTES.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
	AND SHISTDISCPENDENTES.RA = SHISTDISCCONCLUIDAS.RA
	AND SHISTDISCPENDENTES.IDHABILITACAOFILIAL = SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL
	AND SDGC.ZERARCREDFINRECALC IS NULL
GROUP BY 
	SHISTDISCPENDENTES.CODCOLIGADA,
	SHISTDISCPENDENTES.RA,
	SHISTDISCPENDENTES.IDHABILITACAOFILIAL


) AS PENDENTES
	
	

WHERE SGRADE.STATUS <> 1
AND SHABILITACAOFILIAL.CODTIPOCURSO = 1



GROUP BY SGRADE.CARGAHORARIA,
A.EMCURSO,
SALUNO.RA,
SINSTITUICAO.NOMEFANTASIA,
PPESSOA.NOME,
SHABILITACAOFILIAL.IDHABILITACAOFILIAL,
PPESSOA.CPF,
A.TOTALATIV,
SSTATUS.DESCRICAO,
GFILIAL.NOMEFANTASIA,
STIPOCURSO.NOME,
OPT.TOPTATIVAS,
PENDENTES.TOTAL,
SCURSOMEC.CODINEPCURSO,
DISCGRADE.TDISC,
SCURSO.NOME,
SCAMPUS.DESCRICAO,
SCAMPUS.CAMPUSMEC,
DTPERLET.DTINICIO,
SGRADE.DESCRICAO,
B.TCOMPOMENTE,
SPESSOA.ANOULTIMAINST,
A.DISCEMCURSO,
STURNO.NOME,
SINSTITUICAOMEC.CODEMEC,
SGRAU.DESCRICAO,
SCURSO.CODCURSO



HAVING ISNULL(CAST((((DISCGRADE.TDISC+ISNULL(OPT.TOPTATIVAS,0)) *100) / (SGRADE.CARGAHORARIA - B.TCOMPOMENTE) ) AS DECIMAL(10,2)),0) <= :PERCE
	AND SCURSO.CODCURSO = :CODCURSO
	


END


