-- Apresenta Disciplinas, dia da semana e horarios de aulas

SELECT
	codperlet Periodo,
	f.nome NomFiial,
	c.CODCURSO,
	c.NOME NomCurso,
	STURMADISC.CODTURMA,
	STURMADISC.idturmadisc,
	STURMADISCCOMPL.TIPOTURMADISC TipoTurma,
	STURMADISCCOMPL.IDCANVAS,
	t.NOME NomTurma,
	SDISCIPLINA.NOME NomDisciplina,
	PPESSOA.NOME Professor,
	SPROFESSORTURMA.TIPOPROF TipoProf,
	SPROFESSORTURMA.CODPROF,
	case isnull(SHORARIO.DIASEMANA, 0)
		when 0 then '_Não Informado'
		when 1 then 'Domingo'
		when 2 then 'Segunda'
		when 3 then 'Terça'
		when 4 then 'Quarta'
		when 5 then 'Quinta'
		when 6 then 'Sexta'
		when 7 then 'Sábado'
	end DIASEMANA,
	isnull(SHORARIO.HORAINICIAL,'00:00') HoraInicial,
	isnull(SHORARIO.HORAFINAL,'00:00') HoraFinal,
	1 AS NomDisciplina/*SDISCIPLINA.NOME NomDisciplina*/
FROM 
	STURMADISC
	inner join STURMA (nolock) t on t.CODCOLIGADA = STURMADISC.CODCOLIGADA and t.CODFILIAL = STURMADISC.CODFILIAL and t.CODTURMA = STURMADISC.CODTURMA and t.IDPERLET = STURMADISC.IDPERLET
	inner join SHABILITACAOFILIAL (nolock) hf on hf.CODCOLIGADA = t.CODCOLIGADA and hf.IDHABILITACAOFILIAL = t.IDHABILITACAOFILIAL
	inner join GFILIAL (nolock) f on f.CODCOLIGADA=hf.CODCOLIGADA and f.CODFILIAL = hf.CODFILIAL
	inner join SCURSO (nolock) c on c.CODCOLIGADA=hf.CODCOLIGADA and c.CODCURSO=hf.CODCURSO
	INNER JOIN SPLETIVO (nolock) ON STURMADISC.IDPERLET = SPLETIVO.IDPERLET 
	INNER JOIN SDISCIPLINA (nolock) ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
	LEFT JOIN SHORARIOTURMA (nolock) ON STURMADISC.CODCOLIGADA =  SHORARIOTURMA.CODCOLIGADA AND STURMADISC.IDTURMADISC =  SHORARIOTURMA.IDTURMADISC 
	LEFT JOIN SHORARIO (nolock) ON SHORARIO.CODCOLIGADA = SHORARIOTURMA.CODCOLIGADA AND SHORARIO.CODHOR = SHORARIOTURMA.CODHOR
	LEFT JOIN SPROFESSORTURMA (nolock) ON SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
	LEFT JOIN SPROFESSOR (nolock) ON SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	LEFT JOIN PPESSOA (nolock) ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
	LEFT JOIN STURMADISCCOMPL ON STURMADISCCOMPL.IDTURMADISC = STURMADISC.IDTURMADISC
WHERE 
	CODPERLET IN (:CODPERLET)
	