-- Mostra os perfis de acesso do usuario do professor

SELECT
	DISTINCT
	GUSRPERFIL.CODPERFIL -- Nome do perfil que o professor tem acesso

FROM  SPROFESSOR (NOLOCK)
	LEFT JOIN PPESSOA (NOLOCK)
		ON SPROFESSOR.CODPESSOA = PPESSOA.CODIGO
	LEFT JOIN GUSUARIO (NOLOCK)
		ON PPESSOA.CODUSUARIO = GUSUARIO.CODUSUARIO
	LEFT JOIN GUSRPERFIL (NOLOCK)
		ON GUSUARIO.CODUSUARIO = GUSRPERFIL.CODUSUARIO
WHERE SPROFESSOR.CODPROF = :CODPROF

