-- Vê qual é o perfil de acesso do professor

SELECT
	NOME,
	GUSRPERFIL.CODUSUARIO,
	CODSISTEMA,
	CODPERFIL
FROM  GUSRPERFIL(NOLOCK)
	INNER JOIN GUSUARIO (NOLOCK)
		ON GUSUARIO.CODUSUARIO = GUSRPERFIL.CODUSUARIO
	INNER JOIN SPROFESSOR (NOLOCK)
		ON GUSUARIO.CODUSUARIO = SPROFESSOR.CODPESSOA
WHERE SPROFESSOR.CODPROF = 364

select * from sprofessor 
select * from GUSUARIO