Select 
	DISTINCT
	pt.CODPROF
	
from 
	SPROFESSORTURMA pt
	inner join STURMADISC td on td.CODCOLIGADA=pt.CODCOLIGADA and pt.IDTURMADISC=td.IDTURMADISC
	inner join SPLETIVO pl on pl.CODCOLIGADA=td.CODCOLIGADA and pl.IDPERLET=td.IDPERLET
Where
	pl.CODPERLET like :ANO + '%' 
AND pt.DTINICIO >= '20220207 00:00:00.000'
AND pt.DTFIM <= '20221216 00:00:00.000'