
--Versão 4 
SELECT 
STURMADISC.IDTURMADISC

FROM STURMADISC (NOLOCK)
INNER JOIN SPLETIVO  (NOLOCK) ON STURMADISC.IDPERLET = SPLETIVO.IDPERLET
LEFT JOIN SHORARIOTURMA (NOLOCK)  ON STURMADISC.IDTURMADISC=  SHORARIOTURMA.IDTURMADISC
LEFT JOIN SHORARIOPROFESSOR (NOLOCK) ON SHORARIOPROFESSOR.IDHORARIOTURMA = SHORARIOTURMA.IDHORARIOTURMA
WHERE 
SPLETIVO.CODPERLET = :PERIODO_LETIVO
AND SHORARIOPROFESSOR.IDPROFESSORTURMA IS NULL