-- Lista professores por curso e filial e outras informaçãoes do professor

SELECT 
		DISTINCT
	v_unasp_STURMADISC.CODPERLET AS 'Periodo Letivo',
	NOMFILIAL AS 'Filial', 
	NOMTIPOCURSO AS 'Tipo Curso',
	NOMCURSO AS 'Curso',
	PPESSOA.NOME AS 'Nome',
	PPESSOA.CPF AS CPF,
	STITULACAO.NOME AS 'Titulação',
	PPESSOA.EMAIL AS 'E-mail Comercial',
	PPESSOA.EMAILPESSOAL AS 'E-mail Pessoal',
	PPESSOA.TELEFONE1 AS 'Celular',
	PPESSOA.TELEFONE2 AS 'Residencial',
	PPESSOA.TELEFONE3 AS 'Comercial'
	
FROM 
	v_unasp_STURMADISC (NOLOCK) 
	INNER JOIN  SPROFESSORTURMA SPROFESSORTURMA (NOLOCK) 
		ON SPROFESSORTURMA.CODCOLIGADA=v_unasp_STURMADISC.CODCOLIGADA and SPROFESSORTURMA.IDTURMADISC=v_unasp_STURMADISC.IDTURMADISC
	LEFT JOIN SPROFESSOR (NOLOCK)
		ON SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	LEFT JOIN PPESSOA (NOLOCK)
		ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
	LEFT JOIN STITULACAO (NOLOCK)
		ON STITULACAO.CODTITULACAO = SPROFESSOR.CODTITULACAO
WHERE
	CODPERLET = :Pediodo_Let
	and NOMCURSO  IS NOT NULL

ORDER BY NomCurso, NOME