-- Rascunho
select * from SHISTDISCOPTELETIVAS --(IDHANILITACAO, RA, PLETIVO,CODDISC, DISCIPLINA, STATUS DISCIPLINA, NOTA, FALTAS,IDTURMADISC)
select * from SHISTDISCEQUIVCONCLUIDAS -- Possui mais linhas que a anterior(IDHANILITACAO, RA, PLETIVO,CODDISC, DISCIPLINA, STATUS DISCIPLINA,NUMCREDITOS, NOTA, FALTAS,IDTURMADISC)
select distinct STATUS  from SHISTDISCCONCLUIDAS -- ()
select distinct STATUS  from SHISTDISCPENDENTES 
select * from SPARAM 
select * from SMATRICULA --(IDTURMADISC, RA, IDPERLET, IDHABILITACAOFILIAL, TIPOMAT, TIPODISCIPLINA)
select * from STURMADISC -- ()
select * from v_Unasp_SHABILITACAOFILIALPL -- IDPERLET, IDHABILITACAOFILIAL
select * from sstatus -- Status Da diciplina
select * from ppessoa -- Nome 
SELECT * FROM SPLETIVO 
sp_help SPARAM 

-- Inicio de código

-- RAs para teste de Equivalencia: (000303), maik 002822, MARCELLA 013170 ; MURILO 059797


select  DC. PLETIVO, HF.NomFilial, HF.NomCurso, HF.NomTipoCurso, NomTurno, PPESSOA.NOME, DC.RA, DC.DISCIPLINA,DC.STATUS AS StatusDisciplina, DC.NOTA, DC.FALTAS, HF.NomGrade AS NomeMatriz, HF.CODGRADE,HF.Status AS StatusMatriz, [DISCEQUIV] = 
      CASE
	  WHEN DC.NOTA IS NULL THEN 'Possível EQUIV'  
	  ELSE 'Regular' END
from SHISTDISCCONCLUIDAS DC (NOLOCK)
	INNER JOIN SHISTDISCEQUIVCONCLUIDAS DEC (NOLOCK)
		ON DC.IDHABILITACAOFILIAL = DEC.IDHABILITACAOFILIAL AND DC.RA = DEC.RA
	LEFT JOIN STURMADISC (NOLOCK)
		ON  DC.IDTURMADISC = STURMADISC.IDTURMADISC
	LEFT JOIN v_Unasp_SHABILITACAOFILIALPL HF (NOLOCK)
		ON HF.IDHABILITACAOFILIAL = DC.IDHABILITACAOFILIAL AND HF.IDPERLET = DC.IDPERLET
	LEFT JOIN PPESSOA (NOLOCK)
		ON PPESSOA.CODIGO = DC.RA
	
	where DC.RA = :RA 
	AND DC.PLETIVO IS NOT NULL 
	
UNION


select DEC.PLETIVO, null, null, null, null, null, DEC.RA, DEC.DISCIPLINA,DEC.STATUS, DEC.NOTA, DEC.FALTAS, null, null, null ,[DISCEQUIV] = 
	CASE
     WHEN DC.DISCIPLINA IS NOT NULL THEN 'EQUIV'END
from SHISTDISCEQUIVCONCLUIDAS DEC (NOLOCK)
	INNER JOIN SHISTDISCCONCLUIDAS DC (NOLOCK)
		ON  DEC.IDHABILITACAOFILIAL = DC.IDHABILITACAOFILIAL AND DEC.RA = DC.RA
	
WHERE DC.RA = :RA




-- Teste
		SELECT RA, DISCIPLINA, NOTA,  [EQVA] = CASE WHEN NOTA IS NULL  THEN 'Equivalente' ELSE ' ' END FROM SHISTDISCCONCLUIDAS
		WHERE RA = 002822

		