-- Rascunho Tabelas
select * from SHISTDISCOPTELETIVAS --(IDHANILITACAO, RA, PLETIVO,CODDISC, DISCIPLINA, STATUS DISCIPLINA, NOTA, FALTAS,IDTURMADISC)
select * from SHISTDISCEQUIVCONCLUIDAS -- Possui mais linhas que a anterior(IDHANILITACAO, RA, PLETIVO,CODDISC, DISCIPLINA, STATUS DISCIPLINA,NUMCREDITOS, NOTA, FALTAS,IDTURMADISC)
select distinct STATUS  from SHISTDISCCONCLUIDAS -- ()
select distinct STATUS  from SHISTDISCPENDENTES 
select * from SPARAM 
select * from SMATRICULA --(IDTURMADISC, RA, IDPERLET, IDHABILITACAOFILIAL, TIPOMAT, TIPODISCIPLINA)
select * from STURMADISC -- ()
select * from v_Unasp_SHABILITACAOFILIALPL -- IDPERLET, IDHABILITACAOFILIAL
select * from sstatus -- Status Da diciplina
select * from ppessoa -- Nome 
SELECT * FROM SPLETIVO 