-- Histórico de curricular do aluno

SELECT 
	DISTINCT
	ANALISE.PLETIVO,
	ANALISE.Filial,
	HF.NomTipoCurso,
	ANALISE.Curso,
	HF.CodCurso,
	ANALISE.Aluno,
	ANALISE.RA,
	ANALISE.DISCIPLINA,
	ANALISE.STATUS,
	ANALISE.CODDISC AS 'CodDisc',
	ANALISE.CH,
	ANALISE.NOTA AS 'Media',
	ANALISE.FALTAS AS 'Faltas',
	ANALISE.TIPO AS 'Tipo',
	ANALISE.IDHABILITACAOFILIAL AS IdHabilitacaoFilial,
	HF.CodGrade,
	HF.NomGrade,
	HF.Status AS 'Status Grade'

FROM v_Unasp_AnaliseCurricular ANALISE(NOLOCK)
	INNER JOIN v_Unasp_SHABILITACAOFILIALPL HF (NOLOCK)
		ON ANALISE.IDHABILITACAOFILIAL = HF.IDHABILITACAOFILIAL
			AND ANALISE.CODCOLIGADA = HF.CODCOLIGADA
			AND ANALISE.CODTIPOCURSO = HF.CODTIPOCURSO
WHERE RA = :RA 
ORDER BY ANALISE.PLETIVO