select * from SHISTDISCOPTELETIVAS --(IDHANILITACAO, RA, PLETIVO,CODDISC, DISCIPLINA, STATUS DISCIPLINA, NOTA, FALTAS,IDTURMADISC)
select * from SHISTDISCEQUIVCONCLUIDAS -- Possui mais linhas que a anterior(IDHANILITACAO, RA, PLETIVO,CODDISC, DISCIPLINA, STATUS DISCIPLINA,NUMCREDITOS, NOTA, FALTAS,IDTURMADISC)
select * from SHISTDISCCONCLUIDAS -- ()
select * from SHISTDISCPENDENTES 
select * from SPARAM 

sp_help SPARAM 

-- COD
select DC. PLETIVO, DC.RA, DC.DISCIPLINA, DC.NOTA, DC.FALTAS, NULL
from SHISTDISCCONCLUIDAS DC (NOLOCK)
INNER JOIN SHISTDISCEQUIVCONCLUIDAS DEC (NOLOCK)
	ON DC.IDHABILITACAOFILIAL = DEC.IDHABILITACAOFILIAL AND DC.RA = DEC.RA
	where DC.RA = 002822 

UNION

select DEC.PLETIVO, DEC.RA, DEC.DISCIPLINA, DEC.NOTA, DEC.FALTAS ,[DISCEQUIV] = CASE WHEN DEC.DISCIPLINA IS NOT NULL THEN 'EQUIV'  ELSE DC.DISCI'DISCIPLINA' END
from SHISTDISCEQUIVCONCLUIDAS DEC (NOLOCK)
	LEFT JOIN SHISTDISCCONCLUIDAS DC (NOLOCK)
		ON  DEC.IDHABILITACAOFILIAL = DC.IDHABILITACAOFILIAL AND DEC.RA = DC.RA
WHERE DC.RA = 002822 
order by PLETIVO

		SELECT RA, DISCIPLINA, NOTA,  [EQVA] = CASE WHEN NOTA IS NULL  THEN 'Equivalente' ELSE ' ' END FROM SHISTDISCCONCLUIDAS
		WHERE RA = 002822

		
