DECLARE @P1 INT = /*1*/ 1
DECLARE @P4 VARCHAR(MAX) = /*'058421'*/ '002822'

SELECT 
	   ANALISECURRICULAR.RA,
	   ANALISECURRICULAR.CODDISC,
       ANALISECURRICULAR.DISCIPLINA,
	   ISNULL(ANALISECURRICULAR.STATUS, 'A Cursar') as STATUS,
       ANALISECURRICULAR.PLETIVO,
       ANALISECURRICULAR.NUMCREDITOS,
       ANALISECURRICULAR.CH,
       ANALISECURRICULAR.NOTA,
       ANALISECURRICULAR.FALTAS,
       ANALISECURRICULAR.TIPO,
       ANALISECURRICULAR.CODCOLIGADA,
       ANALISECURRICULAR.IDHABILITACAOFILIAL,
       ANALISECURRICULAR.GREQUIV,
       ANALISECURRICULAR.CODPERIODO,
       ANALISECURRICULAR.CONCEITO,
       ANALISECURRICULAR.CONCEITOECTS,
       ANALISECURRICULAR.MINCH,
       ANALISECURRICULAR.MINCREDITOS,
       ANALISECURRICULAR.MINDISCIPLINAS,
       ANALISECURRICULAR.NOME,
       ANALISECURRICULAR.TIPOAVALIACAO,
	   --AQui
	   ANALISECURRICULAR.GREQUIV
FROM   (
SELECT CASE WHEN SHISTDISCEQUIVCONCLUIDAS.CODDISC IS NOT NULL THEN SHISTDISCEQUIVCONCLUIDAS.CODDISC ELSE SHISTDISCCONCLUIDAS.CODDISC END CODDISC,
               CASE WHEN SHISTDISCEQUIVCONCLUIDAS.DISCIPLINA IS NOT NULL THEN SHISTDISCEQUIVCONCLUIDAS.DISCIPLINA ELSE SHISTDISCCONCLUIDAS.DISCIPLINA END DISCIPLINA,
               CASE WHEN SHISTDISCEQUIVCONCLUIDAS.STATUS IS NOT NULL THEN SHISTDISCEQUIVCONCLUIDAS.STATUS ELSE SHISTDISCCONCLUIDAS.STATUS END STATUS,
               CASE WHEN SHISTDISCEQUIVCONCLUIDAS.PLETIVO IS NOT NULL THEN SHISTDISCEQUIVCONCLUIDAS.PLETIVO ELSE SHISTDISCCONCLUIDAS.PLETIVO END PLETIVO,
               CASE WHEN SHISTDISCEQUIVCONCLUIDAS.NUMCREDITOS IS NOT NULL THEN SHISTDISCEQUIVCONCLUIDAS.NUMCREDITOS ELSE SHISTDISCCONCLUIDAS.NUMCREDITOS END NUMCREDITOS,
               CASE WHEN SHISTDISCEQUIVCONCLUIDAS.CH IS NOT NULL THEN SHISTDISCEQUIVCONCLUIDAS.CH ELSE SHISTDISCCONCLUIDAS.CH END CH,
               CASE WHEN SHISTDISCEQUIVCONCLUIDAS.NOTA IS NOT NULL THEN SHISTDISCEQUIVCONCLUIDAS.NOTA ELSE SHISTDISCCONCLUIDAS.NOTA END NOTA,
               CASE WHEN SHISTDISCEQUIVCONCLUIDAS.FALTAS IS NOT NULL THEN SHISTDISCEQUIVCONCLUIDAS.FALTAS ELSE SHISTDISCCONCLUIDAS.FALTAS END FALTAS,
               'CONC' AS TIPO,
               SHISTDISCCONCLUIDAS.CODCOLIGADA,
               SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL,
               SHISTDISCCONCLUIDAS.RA,
               SHISTDISCCONCLUIDAS.GREQUIV,
               SHISTDISCCONCLUIDAS.CODPERIODO,
               SHISTDISCCONCLUIDAS.CONCEITO,
               SHISTDISCCONCLUIDAS.CONCEITOECTS,
			   --Aqui
			   v_unasp_STURMADISC.Ativa,
               NULL   AS MINCH,
               NULL   AS MINCREDITOS,
               NULL   AS MINDISCIPLINAS,
               NULL   AS NOME,
               NULL   AS TIPOAVALIACAO
        FROM   SHISTDISCCONCLUIDAS (NOLOCK)
       	LEFT JOIN DBO.SHISTDISCEQUIVCONCLUIDAS (NOLOCK)
              ON DBO.SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = DBO.SHISTDISCCONCLUIDAS.CODCOLIGADA
                 AND DBO.SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL = DBO.SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL
                 AND DBO.SHISTDISCEQUIVCONCLUIDAS.RA = DBO.SHISTDISCCONCLUIDAS.RA
                 AND DBO.SHISTDISCEQUIVCONCLUIDAS.GREQUIV = DBO.SHISTDISCCONCLUIDAS.GREQUIV	
	    --Para nome do professor
		INNER JOIN v_unasp_STURMADISC (NOLOCK)
			  ON SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = v_unasp_STURMADISC.IDHABILITACAOFILIAL
				 AND SHISTDISCCONCLUIDAS.CODDISC = v_unasp_STURMADISC.CODDISC
				
		/*INNER JOIN  SPROFESSORTURMA (NOLOCK) 
			ON SPROFESSORTURMA.CODCOLIGADA=v_unasp_STURMADISC.CODCOLIGADA and SPROFESSORTURMA.IDTURMADISC=v_unasp_STURMADISC.IDTURMADISC
		LEFT JOIN SPROFESSOR (NOLOCK)
			ON SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
		LEFT JOIN PPESSOA PROFESSORDISC (NOLOCK)
			ON PROFESSORDISC.CODIGO = SPROFESSOR.CODPESSOA*/

        WHERE  SHISTDISCCONCLUIDAS.CODCOLIGADA = @P1
               AND SHISTDISCCONCLUIDAS.RA = @P4
               AND SHISTDISCCONCLUIDAS.CODPERIODO <> 0 
        UNION
        SELECT SHISTDISCPENDENTES.CODDISC,
               SHISTDISCPENDENTES.DISCIPLINA,
               SHISTDISCPENDENTES.STATUS,
               SHISTDISCPENDENTES.PLETIVO,
               SHISTDISCPENDENTES.NUMCREDITOS,
               SHISTDISCPENDENTES.CH,
               SHISTDISCPENDENTES.NOTA,
               SHISTDISCPENDENTES.FALTAS,
               CASE 
					WHEN SHISTDISCPENDENTES.STATUS IS NOT NULL THEN 'PEND' 
					ELSE 'CUR'
			   END AS TIPO,
               SHISTDISCPENDENTES.CODCOLIGADA,
               SHISTDISCPENDENTES.IDHABILITACAOFILIAL,
               SHISTDISCPENDENTES.RA,
               SHISTDISCPENDENTES.GREQUIV,
               SHISTDISCPENDENTES.CODPERIODO,
               SHISTDISCPENDENTES.CONCEITO,
               SHISTDISCPENDENTES.CONCEITOECTS,
               NULL   AS MINCH,
               NULL   AS MINCREDITOS,
               NULL   AS MINDISCIPLINAS,
               NULL   AS NOME,
               NULL   AS TIPOAVALIACAO
        FROM   SHISTDISCPENDENTES (NOLOCK)
        WHERE  SHISTDISCPENDENTES.CODCOLIGADA = @P1
               AND SHISTDISCPENDENTES.RA = @P4
               AND SHISTDISCPENDENTES.CODPERIODO <> 0

        UNION
        SELECT SHISTDISCOPTELETIVAS.CODDISC,
               SHISTDISCOPTELETIVAS.DISCIPLINA,
               SHISTDISCOPTELETIVAS.STATUS,
               SHISTDISCOPTELETIVAS.PLETIVO,
               SHISTDISCOPTELETIVAS.NUMCREDITOS,
               SHISTDISCOPTELETIVAS.CH,
               SHISTDISCOPTELETIVAS.NOTA,
               SHISTDISCOPTELETIVAS.FALTAS,
			   --AQUI
			   SHISTDISCOPTELETIVAS.CH,
               CASE
                 WHEN ( SHISTDISCOPTELETIVAS.CODSTATUSRES IS NOT NULL )
                       OR ( SHISTDISCOPTELETIVAS.STATUS = '*Equiv' ) THEN 'CONC'
                 ELSE 'PEND'
               END AS TIPO,
               SHISTDISCOPTELETIVAS.CODCOLIGADA,
               SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL,
               SHISTDISCOPTELETIVAS.RA,
               SHISTDISCOPTELETIVAS.GREQUIV,
               SGRUPOOPTELET.CODPERIODO,
               SHISTDISCOPTELETIVAS.CONCEITO,
               SHISTDISCOPTELETIVAS.CONCEITOECTS,
               SGRUPOOPTELET.MINCH,
               SGRUPOOPTELET.MINCREDITOS,
               SGRUPOOPTELET.MINDISCIPLINAS,
               SGRUPOOPTELET.NOME,
               SGRUPOOPTELET.TIPOAVALIACAO
        FROM   SPARAM (NOLOCK)
               JOIN SHISTDISCOPTELETIVAS (NOLOCK)
                 ON ( SPARAM.CODCOLIGADA = SHISTDISCOPTELETIVAS.CODCOLIGADA
                      AND SHISTDISCOPTELETIVAS.CODCOLIGADA = @P1
                      AND SHISTDISCOPTELETIVAS.RA = @P4)
               JOIN SHABILITACAOFILIAL (NOLOCK)
                 ON ( SHABILITACAOFILIAL.CODCOLIGADA = SHISTDISCOPTELETIVAS.CODCOLIGADA
                      AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL )
               JOIN SGRUPOOPTELET (NOLOCK)
                 ON ( SHABILITACAOFILIAL.CODCOLIGADA = SGRUPOOPTELET.CODCOLIGADA
                      AND SHABILITACAOFILIAL.CODCURSO = SGRUPOOPTELET.CODCURSO
                      AND SHABILITACAOFILIAL.CODHABILITACAO = SGRUPOOPTELET.CODHABILITACAO
                      AND SHABILITACAOFILIAL.CODGRADE = SGRUPOOPTELET.CODGRADE )
               JOIN SDISCGRUPOOPTELET (NOLOCK)
                 ON ( SGRUPOOPTELET.CODCOLIGADA = SDISCGRUPOOPTELET.CODCOLIGADA
                      AND SGRUPOOPTELET.CODCURSO = SDISCGRUPOOPTELET.CODCURSO
                      AND SGRUPOOPTELET.CODHABILITACAO = SDISCGRUPOOPTELET.CODHABILITACAO
                      AND SGRUPOOPTELET.CODGRADE = SDISCGRUPOOPTELET.CODGRADE
                      AND SGRUPOOPTELET.IDGRUPO = SDISCGRUPOOPTELET.IDGRUPO
                      AND SHISTDISCOPTELETIVAS.CODDISC = SDISCGRUPOOPTELET.CODDISC )
               LEFT JOIN SGRADEALUNO (NOLOCK)
                 ON ( SHISTDISCOPTELETIVAS.CODCOLIGADA = SGRADEALUNO.CODCOLIGADA
                      AND SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL = SGRADEALUNO.IDHABILITACAOFILIAL
                      AND SHISTDISCOPTELETIVAS.RA = SGRADEALUNO.RA )
        WHERE  SPARAM.CODCOLIGADA = @P1
               AND SPARAM.ID = 'USAGRUPOOPTELETIVA'
               AND (SPARAM.TEXTO = '1' OR SPARAM.TEXTO = 'S')
               AND SGRUPOOPTELET.EXIBEANALISE = 'S'
               AND SGRADEALUNO.RA IS NULL
               AND SHISTDISCOPTELETIVAS.RA NOT IN (SELECT SCOMPONENTECURRALUNO.RA
                                                   FROM   SCOMPONENTECURRALUNO (NOLOCK)
                                                   WHERE  SCOMPONENTECURRALUNO.CODCOLIGADA = SHISTDISCOPTELETIVAS.CODCOLIGADA
                                                          AND SCOMPONENTECURRALUNO.IDHABILITACAOFILIAL = SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL
                                                          AND SCOMPONENTECURRALUNO.RA = SHISTDISCOPTELETIVAS.RA)

        UNION
        SELECT SHISTDISCOPTELETIVAS.CODDISC,
               SHISTDISCOPTELETIVAS.DISCIPLINA,
               SHISTDISCOPTELETIVAS.STATUS,
               SHISTDISCOPTELETIVAS.PLETIVO,
               SHISTDISCOPTELETIVAS.NUMCREDITOS,
               SHISTDISCOPTELETIVAS.CH,
               SHISTDISCOPTELETIVAS.NOTA,
               SHISTDISCOPTELETIVAS.FALTAS,
			   --AQUI
			   SHISTDISCOPTELETIVAS.CODCOLIGADA,
               CASE
                 WHEN ( SHISTDISCOPTELETIVAS.CODSTATUSRES IS NOT NULL )
                       OR ( SHISTDISCOPTELETIVAS.STATUS = '*Equiv' ) THEN 'CONC'
                 ELSE 'PEND'
               END AS TIPO,
               SHISTDISCOPTELETIVAS.CODCOLIGADA,
               SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL,
               SHISTDISCOPTELETIVAS.RA,
               SHISTDISCOPTELETIVAS.GREQUIV,
               SGRUPOOPTELETALUNO.CODPERIODO,
               SHISTDISCOPTELETIVAS.CONCEITO,
               SHISTDISCOPTELETIVAS.CONCEITOECTS,
               SGRUPOOPTELETALUNO.MINCH,
               SGRUPOOPTELETALUNO.MINCREDITOS,
               SGRUPOOPTELETALUNO.MINDISCIPLINAS,
               SGRUPOOPTELETALUNO.NOME,
               SGRUPOOPTELETALUNO.TIPOAVALIACAO
        FROM   SPARAM (NOLOCK)
               JOIN SHISTDISCOPTELETIVAS (NOLOCK)
                 ON ( SPARAM.CODCOLIGADA = SHISTDISCOPTELETIVAS.CODCOLIGADA
                      AND SHISTDISCOPTELETIVAS.CODCOLIGADA = @P1
                      AND SHISTDISCOPTELETIVAS.RA = @P4)
               JOIN SGRUPOOPTELETALUNO (NOLOCK)
                 ON ( SHISTDISCOPTELETIVAS.CODCOLIGADA = SGRUPOOPTELETALUNO.CODCOLIGADA
                      AND SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL = SGRUPOOPTELETALUNO.IDHABILITACAOFILIAL
                      AND SHISTDISCOPTELETIVAS.RA = SGRUPOOPTELETALUNO.RA )
               JOIN SDISCGRUPOOPTELETALUNO (NOLOCK)
                 ON ( SGRUPOOPTELETALUNO.CODCOLIGADA = SDISCGRUPOOPTELETALUNO.CODCOLIGADA
                      AND SGRUPOOPTELETALUNO.IDHABILITACAOFILIAL = SDISCGRUPOOPTELETALUNO.IDHABILITACAOFILIAL
                      AND SGRUPOOPTELETALUNO.RA = SDISCGRUPOOPTELETALUNO.RA
                      AND SGRUPOOPTELETALUNO.IDGRUPO = SDISCGRUPOOPTELETALUNO.IDGRUPO
                      AND SHISTDISCOPTELETIVAS.CODDISC = SDISCGRUPOOPTELETALUNO.CODDISC )
               LEFT JOIN SGRADEALUNO (NOLOCK)
                 ON ( SHISTDISCOPTELETIVAS.CODCOLIGADA = SGRADEALUNO.CODCOLIGADA
                      AND SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL = SGRADEALUNO.IDHABILITACAOFILIAL
                      AND SHISTDISCOPTELETIVAS.RA = SGRADEALUNO.RA )
        WHERE  SPARAM.CODCOLIGADA = @P1
               AND SPARAM.ID = 'USAGRUPOOPTELETIVA'
               AND (SPARAM.TEXTO = '1' OR SPARAM.TEXTO = 'S')
               AND SGRUPOOPTELETALUNO.EXIBEANALISE = 'S'
               AND ( SGRADEALUNO.RA IS NOT NULL
                      OR SHISTDISCOPTELETIVAS.RA IN (SELECT SCOMPONENTECURRALUNO.RA
                                                     FROM   SCOMPONENTECURRALUNO (NOLOCK)
                                                     WHERE  SCOMPONENTECURRALUNO.CODCOLIGADA = SHISTDISCOPTELETIVAS.CODCOLIGADA
                                                            AND SCOMPONENTECURRALUNO.IDHABILITACAOFILIAL = SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL
                                                            AND SCOMPONENTECURRALUNO.RA = SHISTDISCOPTELETIVAS.RA) )) ANALISECURRICULAR                                                       
WHERE ANALISECURRICULAR.STATUS <> '*Equiv.' OR ANALISECURRICULAR.STATUS IS NULL
ORDER  BY ANALISECURRICULAR.RA,
          ANALISECURRICULAR.CODPERIODO,
          ANALISECURRICULAR.NOME