/*ALUNOS COM NOME SOCIAL PREENCHIDO OU INCORRETO*/
SELECT	
	DISTINCT
	A.NOME,
	A.NOMESOCIAL 'NOME SOCIAL',
	B.CODPERLET 'PERIODO LETIVO',
	B.NOMFILIAL 'NOME FILIAL',
	B.NOMSTATUS,
	B.RA,
	B.CODTURMA 'COD_TURMA',
	B.NOMDISCIPLINA 'DISCIPLINA',
	B.NOMCURSO 'CURSO',
	B.NOMTIPOCURSO 'TIPO CURSO'

FROM PPESSOA A
INNER JOIN v_Unasp_SMATRICULA B ON A.EMAIL = B.EMAIL
WHERE
	NOMESOCIAL  IS NOT NULL 
AND CODPERLET = :PERIODO_LETIVO
AND NOMSTATUS LIKE '%' + :STATUS + '%'
	