/*Pega todas as avaliações com o campo "Valor" diferente de 10, 
mas somente do "Tipo de cálculo" igual a "Calculo Por Peso". Ignora o Tipo de calculo Bônus.*/

SELECT 
	STURMADISC.IDTURMADISC,
	SPROVAS.VALOR,
	SPROVASCOMPL.TIPO
FROM STURMADISC (NOLOCK)
	LEFT JOIN SPLETIVO  (NOLOCK) ON STURMADISC.IDPERLET = SPLETIVO.IDPERLET
	LEFT JOIN SPROVAS (NOLOCK) ON STURMADISC.IDTURMADISC = SPROVAS.IDTURMADISC   
	LEFT JOIN SPROVASCOMPL (NOLOCK) ON SPROVAS.IDTURMADISC = SPROVASCOMPL.IDTURMADISC
WHERE
	SPLETIVO.CODPERLET = :PER_LETIVO  
AND SPROVAS.VALOR != 10
AND SPROVASCOMPL.TIPO = 'C' 

