/*
Formas de Consulta:
    Cod_Periodo = Periodo Letivo
    Ex: 2022/1, 2022/2, etc..
         
	Cod_Nivel_Ensino = Nível de Ensino 
	Ex: 1 (Para Graduação)e 2 (Para Pós-graduação)
	
	Cod_Filial = Filial
	Ex: 1 (SP), 2 (EC), 3 (HT) e 4 (EAD)
*/
SELECT 
	SPLETIVO.CODPERLET AS Periodo,
	STURMADISC.CODFILIAL AS Filial,
	SDISCIPLINA.CODTIPOCURSO AS 'Nível de Ensino',
	STURMADISC.CODTURMA AS 'Código Turma',
	SCURSO.NOME AS 'Curso',
	STURMADISC.IDTURMADISC AS Código,
	SDISCIPLINA.NOME AS Disciplina,
	STURMADISCCOMPL.TIPOTURMADISC AS 'Tipo Turma',
	PPESSOA.NOME AS Professor,
	COUNT(*)  AS 'Sem Conteúdo',
	STURMA_G.IDTURMADISC AS 'ID Gerencial',
	PESSOA_COORDENADOR.NOME AS 'Coordenador'

	
		
FROM   STURMADISC (NOLOCK)
	LEFT JOIN STURMADISCGERENCIADA (NOLOCK) ON
			STURMADISCGERENCIADA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND STURMADISCGERENCIADA.IDTURMADISCGERENCIADA = STURMADISC.IDTURMADISC	
	LEFT JOIN STURMADISC STURMA_G (NOLOCK) ON
			STURMADISCGERENCIADA.CODCOLIGADA = STURMA_G.CODCOLIGADA
			AND STURMADISCGERENCIADA.IDTURMADISC = STURMA_G.IDTURMADISC
	LEFT JOIN SHABILITACAOFILIAL (NOLOCK)
		ON SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
	LEFT JOIN SCURSO (NOLOCK) 
		ON SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	LEFT JOIN SPLANOAULA (NOLOCK)
		ON SPLANOAULA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND SPLANOAULA.IDTURMADISC = STURMADISC.IDTURMADISC
	LEFT JOIN SDISCIPLINA (NOLOCK)
		ON SDISCIPLINA.CODDISC = STURMADISC.CODDISC
	LEFT JOIN SPLETIVO (NOLOCK)
		ON SPLETIVO.IDPERLET = STURMADISC.IDPERLET
	LEFT JOIN SPROFESSORTURMA (NOLOCK)
		ON SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
	LEFT JOIN SPROFESSOR (NOLOCK)
		ON SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	LEFT JOIN PPESSOA (NOLOCK)
		ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA

	LEFT JOIN SCOORDENADOR (NOLOCK)
		ON SCOORDENADOR.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL 
	
	LEFT JOIN PPESSOA PESSOA_COORDENADOR (NOLOCK)
		ON PESSOA_COORDENADOR.CODIGO = SCOORDENADOR.CODPESSOA 
	LEFT JOIN STURMADISCCOMPL (NOLOCK)
		ON STURMADISCCOMPL.IDTURMADISC = STURMADISC.IDTURMADISC

	

WHERE  SPLANOAULA.CONTEUDOEFETIVO IS NULL
       AND SPLETIVO.CODPERLET = :Cod_Periodo
	   AND SDISCIPLINA.CODTIPOCURSO = :Cod_Nivel_Ensino 
	   AND STURMADISC.CODFILIAL = :Cod_Filial 
	   AND SPLANOAULA.DATA <= Getdate() 
	  
	   

GROUP BY 	STURMADISC.CODFILIAL,
	SDISCIPLINA.CODTIPOCURSO,
	SCURSO.NOME,
	SPLETIVO.CODPERLET ,
	STURMADISC.IDTURMADISC ,
	SDISCIPLINA.NOME ,
	STURMADISCCOMPL.TIPOTURMADISC,
	STURMADISC.CODTURMA,
	PPESSOA.NOME,
	STURMA_G.IDTURMADISC,
    PESSOA_COORDENADOR.NOME

ORDER BY SCURSO.NOME