
--Disciplina SEM horário lançado ou inconpleto
SELECT
	STURMADISC.IDTURMADISC
FROM 
	STURMADISC
	INNER JOIN SPLETIVO (NOLOCK) ON STURMADISC.IDPERLET = SPLETIVO.IDPERLET 
	INNER JOIN SPROFESSORTURMA (NOLOCK) ON SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
	LEFT JOIN SHORARIOTURMA (NOLOCK) ON STURMADISC.CODCOLIGADA =  SHORARIOTURMA.CODCOLIGADA AND STURMADISC.IDTURMADISC =  SHORARIOTURMA.IDTURMADISC 
	INNER JOIN SHORARIO (NOLOCK)  ON SHORARIO.CODCOLIGADA = SHORARIOTURMA.CODCOLIGADA
WHERE 
	SPLETIVO.CODPERLET IN (:CODPERLET)
AND SHORARIOTURMA.IDHORARIOTURMA IS NULL

--Versão 2
SELECT
	*
FROM 
	STURMADISC
	INNER JOIN SPLETIVO (NOLOCK) ON STURMADISC.IDPERLET = SPLETIVO.IDPERLET 
	INNER JOIN SPROFESSORTURMA (NOLOCK) ON SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
	LEFT JOIN SHORARIOTURMA (NOLOCK) ON STURMADISC.CODCOLIGADA =  SHORARIOTURMA.CODCOLIGADA AND STURMADISC.IDTURMADISC =  SHORARIOTURMA.IDTURMADISC 
	INNER JOIN SHORARIO (NOLOCK)  ON SHORARIO.CODCOLIGADA = SHORARIOTURMA.CODCOLIGADA
WHERE 
	SPLETIVO.CODPERLET IN (:CODPERLET)
AND SHORARIOTURMA.IDHORARIOTURMA IS NULL


