SELECT DISTINCT
	SPLETIVO.CODPERLET AS 'Periodo Letivo',
	NomFilial AS 'Filial',
	PPESSOA.NOME AS 'Professor'
	

FROM SPROFESSOR
INNER JOIN SPROFESSORTURMA ON SPROFESSORTURMA.CODCOLIGADA = SPROFESSOR.CODCOLIGADA
	AND SPROFESSORTURMA.CODPROF = SPROFESSOR.CODPROF
INNER JOIN STURMADISC ON STURMADISC.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
	AND STURMADISC.IDTURMADISC = SPROFESSORTURMA.IDTURMADISC
INNER JOIN SPLETIVO ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
	AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET
LEFT JOIN PPESSOA ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
LEFT JOIN v_unasp_STURMADISC ON v_unasp_STURMADISC.IDTURMADISC = STURMADISC.IDTURMADISC

WHERE SPLETIVO.CODPERLET  >= '2018%'
order by SPLETIVO.CODPERLET, PPESSOA.NOME
