/* 
Lista disciplinas com lançamento de créditos errados
*/
SELECT 
STURMADISC.IDTURMADISC 

FROM STURMADISC (NOLOCK)
INNER JOIN SPLETIVO  (NOLOCK) ON STURMADISC.IDPERLET = SPLETIVO.IDPERLET
INNER JOIN SHORARIOTURMA (NOLOCK)  ON STURMADISC.IDTURMADISC=  SHORARIOTURMA.IDTURMADISC
LEFT JOIN SDISCIPLINA (NOLOCK) ON SDISCIPLINA.CODDISC = STURMADISC.CODDISC AND SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
GROUP BY  STURMADISC.IDTURMADISC,SDISCIPLINA.NUMCREDITOS

HAVING 
	COUNT(SHORARIOTURMA.CODHOR) != SDISCIPLINA.NUMCREDITOS 
