SELECT STURMADISC.IDTURMADISC
	FROM STURMADISC (NOLOCK)
		INNER JOIN SPLETIVO (NOLOCK) ON
			SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET
			AND SPLETIVO.CODFILIAL = STURMADISC.CODFILIAL
			AND SPLETIVO.CODTIPOCURSO = STURMADISC.CODTIPOCURSO
		INNER JOIN SDISCIPLINA (NOLOCK) ON
			SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
		INNER JOIN SHORARIO (NOLOCK) ON SHORARIO.CODCOLIGADA = STURMADISC.CODCOLIGADA
			    OUTER APPLY (SELECT COUNT(AULA)QTDE
						FROM SPLANOAULA
      				 WHERE IDTURMADISC = STURMADISC.IDTURMADISC)AULAS
WHERE STURMADISC.CODCOLIGADA = :$CODCOLIGADA
AND STURMADISC.CODFILIAL = :$CODFILIAL
AND STURMADISC.CODTIPOCURSO = :$CODTIPOCURSO
AND SPLETIVO.CODPERLET = :CODPERLET_S
AND SDISCIPLINA.NUMCREDITOS = :CREDITOS_N
AND AULAS.QTDE < (SDISCIPLINA.NUMCREDITOS * 20)
AND SHORARIO.DIASEMANA = :DIASEMANA

--FLT.DISCXPLANO	