CREATE PROCEDURE [dbo].[EXCLUI_HORARIO_PLANO_AULA_FREQUENCIA_DA_TURMA] (
@pCODCOLIGADA AS INT,
@pCODFILIAL AS INT,
@pCODTIPOCURSO AS INT,
@pIDTURMADISC AS INT
) AS
BEGIN

	SET @pIDTURMADISC = (SELECT TOP 1 B.IDTURMADISC
		FROM SHORARIOPROFESSOR A (NOLOCK)
		INNER JOIN SHORARIOTURMA AS B (NOLOCK) ON (B.CODCOLIGADA = A.CODCOLIGADA
												  AND B.IDHORARIOTURMA = A.IDHORARIOTURMA)
		INNER JOIN STURMADISC AS C (NOLOCK) ON (C.CODCOLIGADA = B.CODCOLIGADA
											   AND C.IDTURMADISC = B.IDTURMADISC)
		INNER JOIN SPLETIVO AS D (NOLOCK) ON (D.CODCOLIGADA = C.CODCOLIGADA
											 AND D.IDPERLET = C.IDPERLET)
		INNER JOIN SHABILITACAOFILIAL AS E (NOLOCK) ON (E.CODCOLIGADA = C.CODCOLIGADA
													   AND E.IDHABILITACAOFILIAL = C.IDHABILITACAOFILIAL)
		WHERE A.CODCOLIGADA = @pCODCOLIGADA
		AND C.CODFILIAL = @pCODFILIAL
		AND C.CODTIPOCURSO = @pCODTIPOCURSO
		AND C.IDTURMADISC = @pIDTURMADISC);


		DELETE FROM SFREQUENCIA
		WHERE CODCOLIGADA = @pCODCOLIGADA
		AND IDTURMADISC = @pIDTURMADISC;

		DELETE FROM SPLANOAULA
		WHERE IDTURMADISC = @pIDTURMADISC
		AND CODFILIAL = @pCODFILIAL
		AND CODCOLIGADA = @pCODCOLIGADA;

		DELETE FROM SHORARIOPROFESSOR
		FROM SHORARIOPROFESSOR A (NOLOCK)
		INNER JOIN SHORARIOTURMA AS B (NOLOCK) ON (B.CODCOLIGADA = A.CODCOLIGADA
												  AND B.IDHORARIOTURMA = A.IDHORARIOTURMA)
		INNER JOIN STURMADISC AS C (NOLOCK) ON (C.CODCOLIGADA = B.CODCOLIGADA
											   AND C.IDTURMADISC = B.IDTURMADISC)
		INNER JOIN SPLETIVO AS D (NOLOCK) ON (D.CODCOLIGADA = C.CODCOLIGADA
											 AND D.IDPERLET = C.IDPERLET)
		INNER JOIN SHABILITACAOFILIAL AS E (NOLOCK) ON (E.CODCOLIGADA = C.CODCOLIGADA
													   AND E.IDHABILITACAOFILIAL = C.IDHABILITACAOFILIAL)
		INNER JOIN SPROFESSORTURMA AS F (NOLOCK) ON (F.CODCOLIGADA = C.CODCOLIGADA
													AND F.IDTURMADISC = C.IDTURMADISC)

		WHERE A.CODCOLIGADA = @pCODCOLIGADA
		AND C.CODFILIAL = @pCODFILIAL
		AND C.CODTIPOCURSO = @pCODTIPOCURSO
		AND C.IDTURMADISC = @pIDTURMADISC;


		DELETE FROM SHORARIOTURMA
		WHERE CODFILIAL = @pCODFILIAL
		AND CODCOLIGADA = @pCODCOLIGADA
		AND IDTURMADISC = @pIDTURMADISC;
	
END;